version: "3.7"

services:
  server:
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    build: .
    environment:
      PORT: ${PORT}

      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DATABASE: ${DATABASE_DATABASE}
